from time import sleep


SCREEN_WIDTH = 800
SCREEN_HEIGHT = 800
IP_ADDRESS = "127.0.0.1"
PORT = 5555
VEHICLE_WIDTH = 78
VEHICLE_HEIGHT = 82
VEHICLE_VELOCITY = 10
BARREL_CALIBER = 16
BARREL_LENGTH = 50
BULLET_CALIBER = 12
BULLET_LENGTH = 20
BULLET_VELOCITY = 25
DOWN_BARREL_HORIZONTAL_OFFSET = -9
DOWN_BARREL_VERTICAL_OFFSET = -10
UP_BARREL_HORIZONTAL_OFFSET = -10
UP_BARREL_VERTICAL_OFFSET = -50
LEFT_BARREL_HORIZONTAL_OFFSET = -50
LEFT_BARREL_VERTICAL_OFFSET = -11
RIGHT_BARREL_HORIZONTAL_OFFSET = -8
RIGHT_BARREL_VERTICAL_OFFSET = -12
MAP_ROWS = 10
MAP_COLUMNS = 10
INTERVAL_HORIZONTAL = SCREEN_WIDTH/MAP_COLUMNS
INTERVAL_VERTICAL = SCREEN_HEIGHT/MAP_ROWS


GREEN = (0, 255, 0)
RED = (255, 0, 0)

CLIENT_STARTING_POSITIONS = [(0,0), (SCREEN_WIDTH - VEHICLE_WIDTH,0), (0,SCREEN_HEIGHT - VEHICLE_HEIGHT), (SCREEN_WIDTH - VEHICLE_WIDTH, SCREEN_HEIGHT - VEHICLE_HEIGHT)]

UP_UNIT_VECTOR = (0, -1)
DOWN_UNIT_VECTOR = (0, 1)
LEFT_UNIT_VECTOR = (-1, 0)
RIGHT_UNIT_VECTOR = (1, 0)
CLIENT_STARTING_DIRECTION_VECTOR = [(1, 0), (1,0), (-1, 0), (-1, 0)]


def read_pos_team(string: str):
    string = string.split(",")
    return int(string[0]), int(string[1]), string[2]


def make_pos_team(tup):
    return str(tup[0]) + "," + str(tup[1]) + "," + str(tup[2])


